# Probabilidades

## Objetivos:

Aplicar el enfoque frecuentista para calcular probabilidades simples, conjuntas y condicionales para apoyar la toma de decisiones. Utilizando Python como herramienta de apoyo.

*Nota: Este laboratorio está diseñado para desarrollar razonamiento estadístico. Evita el uso de herramientas de IA para responder las preguntas a menos que esto sea explícitamente sugerido* 🤖. *En su lugar, enfócate en aplicar los conceptos revisados.*

## Actividad 1

1. Clasifica cada uno de los siguientes experimentos como Aleatorio o Determinista.

| Experimento | Suceso | Clasificación |
|-------------|--------|----------------|
| Jugar un boleto en un juego de lotería | Ganar algún premio en la lotería | **Aleatorio** |
| Calcular un ángulo interior de un cuadrado cualquiera | El ángulo es recto |**Determinista** |
| Determinar la cantidad de lluvia que caerá la próxima vez que llueva | Caen entre 20 y 50 mm de agua | **Aleatorio**|
| Calcular el número de días que tiene el mes de diciembre | Tiene 31 días |**Determinista** |
| Determinar el país del equipo ganador en el próximo campeonato mundial | El país es Chile |**Aleatorio** |
| Lanzar un dado de seis caras | El resultado es 6 |**Aleatorio** |

2. La siguiente tabla resume el tipo de parentesco con el(la) jefe de hogar obtenido en la Encuesta Nacional de Empleo (ENE), realizada el año 2018 entre los meses de septiembre a noviembre.

<center>

| Parentesco            | Frecuencia |
| ----------------------|:----------:|
| Conviviente           | 49         |            
| Cónyuge               | 141        |            
| Hermano(a) o Cuñado(a)| 16         |            
| Hijo(a) o Hijastro(a) | 347        |            
| Jefe(a) de Hogar      | 335        |            
| Nieto(a)              | 75         |            
| No Pariente           | 4          |            
| Otro Pariente         | 18         |            
| Padres o Suegros      | 16         |      
| Yerno o Nuera         | 11         |  
| **Total General**     | **1012**   |

Si se le preguntase a cualquiera de las personas ya encuestadas su parentesco con el(la) jefe(a) de hogar, ¿cuál sería el resultado más probable? ¿Y el menos probable? Justifique su respuesta.

In [2]:
import pandas as pd

tabla_1= pd.DataFrame({
    "Parentesco: ": ["Conviviente", "Conyuge", "hermano_cuñado", "hijo_hijastro", "jefe_hogar","nieto", "no_pariente", "otro__pariente","padres_suegros","yerno_nuera"],
    "Frecuencia": [49,141,16,347,335,75,4 ,18,16,11]
})

total=1012
tabla_1["Probabilidad %"] = (tabla_1["Frecuencia"]/total)*100

round(tabla_1,1)

     Parentesco:   Frecuencia  Probabilidad %
0     Conviviente          49             4.8
1         Conyuge         141            13.9
2  hermano_cuñado          16             1.6
3   hijo_hijastro         347            34.3
4      jefe_hogar         335            33.1
5           nieto          75             7.4
6     no_pariente           4             0.4
7  otro__pariente          18             1.8
8  padres_suegros          16             1.6
9     yerno_nuera          11             1.1

la mas probable es hijo hijastro, y la menos probable es no pariente

## Actividad 2

El Instituto de Seguridad Laboral recopiló información sobre los accidentes laborales fatales ocurridos en Chile entre los años 2007 y 2016, clasificándolos por grupo etario, género y región donde ocurrieron. La **<a href="https://docs.google.com/spreadsheets/d/1HBf8V23teQNaeaGkWksi0d-HxZGohUgO/export?format=xlsx
">base de datos</a>** de esta actividad incluye un registro por cada accidente reportado.

1. Construye una tabla de frecuencias absolutas que muestre la cantidad total de accidentes fatales, por grupo de edad y género. Luego, responde las siguientes preguntas utilizando la fórmula:

$$P(A) = \frac{Casos \ favorables}{Casos \ totales}$$

In [5]:
df=pd.read_excel("/content/Base7_2.xlsx")

Tabla2 = pd.crosstab( df["GRUPO"], df['GENERO'],
                     margins= True)
Tabla2

GENERO   Hombre  Mujer  All
GRUPO
15 a 19       9      1   10
20 a 24      33      0   33
25 a 29      49      4   53
30 a 34      42      1   43
35 a 39      67      5   72
40 a 44      53      9   62
45 a 49      61      2   63
50 a 54      47      3   50
55 a 59      27      5   32
60 a 64      28      0   28
65 a 69      15      0   15
70 a 74       4      1    5
75 a 79       5      0    5
All         440     31  471

2. Al seleccionar un registro al azar, ¿cuál es la probabilidad de que corresponda a una mujer? ¿Y de que corresponda a un hombre? ¿Cómo se podría explicar esta diferencia?

In [6]:
p_masculino=(440/471)*100

p_femenino=31/471*100

print(p_masculino)
print(p_femenino)

93.41825902335457
6.581740976645436

3.  Si se escoge el registro de un accidente al azar, ¿cuál es la probabilidad que sea el de:  

$\hspace{1.5cm}$ a)  una persona de entre 40 y 49 años?

$\hspace{1.5cm}$ b) una persona de a lo más 34 años?

$\hspace{1.5cm}$ c) un hombre de al menos 40 años?

$\hspace{1.5cm}$ d) una mujer de 70 años o más?

In [10]:
per=62+63

total=471
prob=(per/total)*100
print(prob)

#b
per2=10+33+53+43

prob2=(per2/total)*100

print(prob2)

#c
per3=53+61+47+27+28+15+4+5
prob3=(per3/total)*100

print(prob3)

#d

per4=1

prob=(per4/total)*100

print(prob)

26.53927813163482
29.511677282377917
50.955414012738856
0.21231422505307856

4. Si se escoge aleatoriamente el registro de un accidente y este resulta ser de una mujer, ¿cuál es la probabilidad que sea del grupo de 35 a 39 años?

5. Si se escoge aleatoriamente el registro de un accidente y este resulta ser de un hombre, ¿cuál es la probabilidad que tenga 55 años o más?

## Actividad 3

Una empresa de tecnología ha recolectado datos de los tickets ingresados en su sistema de soporte técnico durante el último mes. Cada ticket incluye el tipo de solicitud (Fallo de hardware, Fallo de software, Fallo de red o Requerimiento funcional), la urgencia (Alta, Media o Baja) y el estado (Resuelto o Pendiente).

Importa la **<a href="https://docs.google.com/spreadsheets/d/1x0Zxj-juwv0BXkLIDtKziTNihsL8AVjo/export?format=xlsx
">base de datos</a>** y responde las siguientes preguntas:

1. Si se selecciona un ticket al azar, ¿cuál es la probabilidad de que sea una solicitud de tipo Fallo de red?

2. ¿Cuál es la probabilidad de que un ticket seleccionado al azar sea del tipo Falla de software y tenga urgencia baja?

3. Si se selecciona un ticket al azar, ¿cuál es la probabilidad de que sea de tipo Fallo de hardware o que aún esté pendiente?

4. ¿Cuál es la probabilidad de que un ticket esté resuelto, dado que es de tipo Fallo de hardware?

5. Si se selecciona un ticket al azar, ¿cuál es la probabilidad de que sea una solicitud de urgencia alta?

6. ¿Cuál es la probabilidad de que un ticket sea de tipo Fallo de red y esté pendiente?

7. ¿Cuál es la probabilidad de que un ticket tenga urgencia alta, dado que es de tipo Fallo de red?

8. ¿Cuál es la probabilidad de que un ticket esté resuelto, dado que tiene urgencia baja?

9. ¿Cuál es la probabilidad de que un ticket sea de tipo Requerimiento funcional o esté resuelto?

## Actividad 4

Un equipo de administración de redes analizó más de 200 incidentes registrados, clasificando el tipo de falla (Conexión, DNS, Firewall, Latencia), el día de la semana en que ocurrió, y si fue causada por error humano o no.

Importa la **<a href="https://drive.google.com/uc?export=download&id=1MsQUDY51dL6a2s1O4h1i_uucAhliqOIF
">base de datos</a>** y responde las siguientes preguntas:

1. Según los datos, ¿qué tipo de falla presenta la mayor probabilidad de ocurrencia?

2. Un integrante del equipo de redes afirma que es más probable que se presenten incidentes los días viernes, por lo que sugiere asignar más personal ese día. ¿Tiene razón en su afirmación? Justifica tu respuesta.

3. Considerando que hay mayor probabilidad de que ocurran fallas los lunes, ¿cuál es la falla más común durante este día de la semana?

4. El equipo de redes está evaluando en qué día de la semana suelen producirse más errores humanos para diseñar mejores estrategias de capacitación y prevención. Si se produce un error humano, ¿cuál es el día más probable en que haya ocurrido?

5. Se ha detectado que muchas configuraciones incorrectas en los firewalls generan interrupciones de servicio. Para evaluar si este tipo de falla está efectivamente asociado a errores humanos, el equipo decide revisar los registros. Dado que la falla registrada es de tipo Firewall, ¿cuál es la probabilidad de que haya sido causada por error humano?

6. El equipo de redes busca identificar momentos críticos en los que ocurren fallas importantes, especialmente aquellas relacionadas con la conexión. ¿Es más probable que una falla ocurra un viernes y sea por Conexión, o que ocurra un sábado y sea por Latencia? Justifica tu respuesta.

7. El equipo de redes ha notado que los domingos suelen ser más exigentes, ya que hay menos personal disponible y cualquier error puede generar retrasos importantes. Además, una parte de las fallas registradas se deben a errores humanos, muchas veces por carga o distracción. Para dimensionar este riesgo, quieren saber: ¿Cuál es la probabilidad de que una falla haya sido causada por error humano o que haya ocurrido un domingo?